/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/invitations': RouteRecordInfo<
      '/admin/invitations',
      '/admin/invitations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/settings': RouteRecordInfo<
      '/admin/settings',
      '/admin/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/users': RouteRecordInfo<
      '/admin/users',
      '/admin/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth': RouteRecordInfo<
      '/auth',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | '/auth/'
      | '/auth/forgot-password'
      | '/auth/login'
      | '/auth/register'
      | '/auth/reset-password'
      | '/auth/verify-email'
    >,
    '/auth/': RouteRecordInfo<
      '/auth/',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/forgot-password': RouteRecordInfo<
      '/auth/forgot-password',
      '/auth/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/login': RouteRecordInfo<
      '/auth/login',
      '/auth/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/register': RouteRecordInfo<
      '/auth/register',
      '/auth/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/reset-password': RouteRecordInfo<
      '/auth/reset-password',
      '/auth/reset-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/verify-email': RouteRecordInfo<
      '/auth/verify-email',
      '/auth/verify-email',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/help': RouteRecordInfo<
      '/help',
      '/help',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/notifications/': RouteRecordInfo<
      '/notifications/',
      '/notifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/': RouteRecordInfo<
      '/projects/',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/[id]': RouteRecordInfo<
      '/projects/[id]',
      '/projects/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | '/projects/[id]/'
      | '/projects/[id]/defects/'
      | '/projects/[id]/dependencies'
      | '/projects/[id]/overview'
      | '/projects/[id]/requirements/'
      | '/projects/[id]/requirements/[requirementId]'
      | '/projects/[id]/settings/'
      | '/projects/[id]/settings/env-vars'
      | '/projects/[id]/settings/general'
      | '/projects/[id]/settings/members'
      | '/projects/[id]/settings/secret-key'
    >,
    '/projects/[id]/': RouteRecordInfo<
      '/projects/[id]/',
      '/projects/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/projects/[id]/defects/': RouteRecordInfo<
      '/projects/[id]/defects/',
      '/projects/:id/defects',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/projects/[id]/dependencies': RouteRecordInfo<
      '/projects/[id]/dependencies',
      '/projects/:id/dependencies',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/projects/[id]/overview': RouteRecordInfo<
      '/projects/[id]/overview',
      '/projects/:id/overview',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/projects/[id]/requirements/': RouteRecordInfo<
      '/projects/[id]/requirements/',
      '/projects/:id/requirements',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/projects/[id]/requirements/[requirementId]': RouteRecordInfo<
      '/projects/[id]/requirements/[requirementId]',
      '/projects/:id/requirements/:requirementId',
      { id: ParamValue<true>, requirementId: ParamValue<true> },
      { id: ParamValue<false>, requirementId: ParamValue<false> },
      | never
    >,
    '/projects/[id]/settings/': RouteRecordInfo<
      '/projects/[id]/settings/',
      '/projects/:id/settings',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/projects/[id]/settings/env-vars': RouteRecordInfo<
      '/projects/[id]/settings/env-vars',
      '/projects/:id/settings/env-vars',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/projects/[id]/settings/general': RouteRecordInfo<
      '/projects/[id]/settings/general',
      '/projects/:id/settings/general',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/projects/[id]/settings/members': RouteRecordInfo<
      '/projects/[id]/settings/members',
      '/projects/:id/settings/members',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/projects/[id]/settings/secret-key': RouteRecordInfo<
      '/projects/[id]/settings/secret-key',
      '/projects/:id/settings/secret-key',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/settings/notifications': RouteRecordInfo<
      '/settings/notifications',
      '/settings/notifications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/password': RouteRecordInfo<
      '/settings/password',
      '/settings/password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/profile': RouteRecordInfo<
      '/settings/profile',
      '/settings/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setup': RouteRecordInfo<
      '/setup',
      '/setup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/invitations.vue': {
      routes:
        | '/admin/invitations'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/settings.vue': {
      routes:
        | '/admin/settings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/users.vue': {
      routes:
        | '/admin/users'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth.vue': {
      routes:
        | '/auth'
        | '/auth/'
        | '/auth/forgot-password'
        | '/auth/login'
        | '/auth/register'
        | '/auth/reset-password'
        | '/auth/verify-email'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/auth/index.vue': {
      routes:
        | '/auth/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/forgot-password.vue': {
      routes:
        | '/auth/forgot-password'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/login.vue': {
      routes:
        | '/auth/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/register.vue': {
      routes:
        | '/auth/register'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/reset-password.vue': {
      routes:
        | '/auth/reset-password'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/auth/verify-email.vue': {
      routes:
        | '/auth/verify-email'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/help.vue': {
      routes:
        | '/help'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/notifications/index.vue': {
      routes:
        | '/notifications/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/projects/index.vue': {
      routes:
        | '/projects/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/projects/[id].vue': {
      routes:
        | '/projects/[id]'
        | '/projects/[id]/'
        | '/projects/[id]/defects/'
        | '/projects/[id]/dependencies'
        | '/projects/[id]/overview'
        | '/projects/[id]/requirements/'
        | '/projects/[id]/requirements/[requirementId]'
        | '/projects/[id]/settings/'
        | '/projects/[id]/settings/env-vars'
        | '/projects/[id]/settings/general'
        | '/projects/[id]/settings/members'
        | '/projects/[id]/settings/secret-key'
      views:
        | 'default'
      pathParamNames:
        | 'id'
    }
    'src/pages/projects/[id]/index.vue': {
      routes:
        | '/projects/[id]/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/projects/[id]/defects/index.vue': {
      routes:
        | '/projects/[id]/defects/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/projects/[id]/dependencies.vue': {
      routes:
        | '/projects/[id]/dependencies'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/projects/[id]/overview.vue': {
      routes:
        | '/projects/[id]/overview'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/projects/[id]/requirements/index.vue': {
      routes:
        | '/projects/[id]/requirements/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/projects/[id]/requirements/[requirementId].vue': {
      routes:
        | '/projects/[id]/requirements/[requirementId]'
      views:
        | never
      pathParamNames:
        | 'requirementId'
    }
    'src/pages/projects/[id]/settings/index.vue': {
      routes:
        | '/projects/[id]/settings/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/projects/[id]/settings/env-vars.vue': {
      routes:
        | '/projects/[id]/settings/env-vars'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/projects/[id]/settings/general.vue': {
      routes:
        | '/projects/[id]/settings/general'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/projects/[id]/settings/members.vue': {
      routes:
        | '/projects/[id]/settings/members'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/projects/[id]/settings/secret-key.vue': {
      routes:
        | '/projects/[id]/settings/secret-key'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/notifications.vue': {
      routes:
        | '/settings/notifications'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/password.vue': {
      routes:
        | '/settings/password'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/settings/profile.vue': {
      routes:
        | '/settings/profile'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/setup.vue': {
      routes:
        | '/setup'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
